print("birthday of chintu is given🍳🔻below")
print("3/1/2012\n")
print("birthday of zenitsu is given🍳🔻below")
print("5/7/2010\n")
print("birthday of sasuke is given🍳🔻below")
print("6/3/2011\n")
print("birthday of gojo is given🍳🔻below")
print("8/2/2009\n")
print("birthday of luffy is given🍳🔻below")
print("7/7/2013\n")